// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 9022fc2a57bb9af2f3ebc2376b98a807812e2e0f
//
pub const NETWORK_MBOX_CSR_ADDR: u32 = 0xc000_0000;
pub mod bits {
    //! Types that represent individual registers (bitfields).
    use tock_registers::register_bitfields;
    register_bitfields! {
        u32,
            pub NetworkMboxCmdStatus [
                /// Indicates the status of network mailbox command.
                Status OFFSET(0) NUMBITS(4) [
                    CmdBusy = 0,
                    DataReady = 1,
                    CmdComplete = 2,
                    CmdFailure = 3,
                ],
            ],
            pub NetworkMboxExecute [
                Execute OFFSET(0) NUMBITS(1) [],
            ],
            pub NetworkMboxHwStatus [
                /// Indicates a correctable ECC single-bit error was
                /// detected and corrected while reading dataout.
                /// Auto-clears when network_mbox_execute field is cleared.
                EccSingleError OFFSET(0) NUMBITS(1) [],
                /// Indicates an uncorrectable ECC double-bit error
                /// was detected while reading dataout.
                /// Firmware developers are advised to set the command
                /// status to CMD_FAILURE in response.
                /// Auto-clears when network_mbox_execute field is cleared.
                EccDoubleError OFFSET(1) NUMBITS(1) [],
            ],
            pub NetworkMboxLock [
                Lock OFFSET(0) NUMBITS(1) [],
            ],
            pub NetworkMboxTargetStatus [
                /// Indicates the status of network mailbox for the target user. Valid when done is set.
                Status OFFSET(0) NUMBITS(4) [
                    CmdBusy = 0,
                    DataReady = 1,
                    CmdComplete = 2,
                    CmdFailure = 3,
                ],
                /// Indicates target user is done and target status is valid.
                Done OFFSET(4) NUMBITS(1) [],
            ],
            pub NetworkMboxTargetUserValid [
                Valid OFFSET(0) NUMBITS(1) [],
            ],
    }
}
pub mod regs {
    //! Types that represent registers.
    use tock_registers::register_structs;
    register_structs! {
        pub NetworkMbox {
            (0x0 => pub network_mbox_sram: [tock_registers::registers::ReadWrite<u32>; 524288]),
            (0x200000 => pub network_mbox_lock: tock_registers::registers::ReadOnly<u32, crate::network_mbox::bits::NetworkMboxLock::Register>),
            (0x200004 => pub network_mbox_user: tock_registers::registers::ReadOnly<u32>),
            (0x200008 => pub network_mbox_target_user: tock_registers::registers::ReadWrite<u32>),
            (0x20000c => pub network_mbox_target_user_valid: tock_registers::registers::ReadWrite<u32, crate::network_mbox::bits::NetworkMboxTargetUserValid::Register>),
            (0x200010 => pub network_mbox_cmd: tock_registers::registers::ReadWrite<u32>),
            (0x200014 => pub network_mbox_dlen: tock_registers::registers::ReadWrite<u32>),
            (0x200018 => pub network_mbox_execute: tock_registers::registers::ReadWrite<u32, crate::network_mbox::bits::NetworkMboxExecute::Register>),
            (0x20001c => pub network_mbox_target_status: tock_registers::registers::ReadWrite<u32, crate::network_mbox::bits::NetworkMboxTargetStatus::Register>),
            (0x200020 => pub network_mbox_cmd_status: tock_registers::registers::ReadWrite<u32, crate::network_mbox::bits::NetworkMboxCmdStatus::Register>),
            (0x200024 => pub network_mbox_hw_status: tock_registers::registers::ReadOnly<u32, crate::network_mbox::bits::NetworkMboxHwStatus::Register>),
            (0x200028 => @END),
        }
    }
}
