// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at dfa6c631dbfc00c8e0c7e6b256619d03d74f0bdc
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
