// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at dfa6c631dbfc00c8e0c7e6b256619d03d74f0bdc
//
pub const USB_DEV1_MEM_ADDR: u32 = 0x3001_0000;
pub mod regs {
    //! Types that represent registers.
    use tock_registers::register_structs;
    register_structs! {
        pub UsbDev1Mem {
            (0x0 => pub usb_dev1_mem: [tock_registers::registers::ReadWrite<u32>; 16384]),
            (0x10000 => @END),
        }
    }
}
