// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at dfa6c631dbfc00c8e0c7e6b256619d03d74f0bdc
//
pub const USB_DEV1_CSR_ADDR: u32 = 0x2000_2000;
pub mod bits {
    //! Types that represent individual registers (bitfields).
    use tock_registers::register_bitfields;
    register_bitfields! {
        u32,
            pub Intsetstat [
                EpSetInt OFFSET(0) NUMBITS(16) [],
                FrameSetInt OFFSET(30) NUMBITS(1) [],
                DevSetInt OFFSET(31) NUMBITS(1) [],
            ],
            pub ClkctrlT [
                /// Set to one to select the external USB clock. When PLL support is absent, this field reads one and ignores writes.
                ExtClkEnable OFFSET(0) NUMBITS(1) [],
            ],
            pub ConfigT [
                /// Reports the configured number of physical endpoints above the two EP0 directions.
                Nbphysep OFFSET(0) NUMBITS(5) [],
                /// Reports whether single-buffer endpoint operation is implemented.
                SingleBuffer OFFSET(5) NUMBITS(1) [],
                /// Reports whether double-buffer endpoint operation is implemented.
                DoubleBuffer OFFSET(6) NUMBITS(1) [],
                /// Reports whether endpoint data-toggle state is readable through EPTOGGLE.
                ToggleReadable OFFSET(7) NUMBITS(1) [],
                /// Reports whether the controller includes programmable PLL clock control.
                Pll OFFSET(8) NUMBITS(1) [],
                /// Reports whether the UTMI+ PHY interface is implemented.
                Utmi OFFSET(9) NUMBITS(1) [],
                /// Reports whether the ULPI PHY interface is implemented.
                Ulpi OFFSET(10) NUMBITS(1) [],
            ],
            pub DatabufstartT [
                /// Programmable portion of the start address for the endpoint data-buffer area.
                DaBuf OFFSET(17) NUMBITS(15) [],
            ],
            pub DevcmdstatT [
                /// USB device address. Software writes update a pending address used during SET_ADDRESS processing; software reads return the committed address. Hardware commits the pending address when the SET_ADDRESS status stage completes.
                DevAddr OFFSET(0) NUMBITS(7) [],
                /// USB device enable.
                DevEn OFFSET(7) NUMBITS(1) [],
                /// SETUP token received.
                Setup OFFSET(8) NUMBITS(1) [],
                /// Set to one to force the NEEDCLK indication active.
                ForceNeedclk OFFSET(9) NUMBITS(1) [],
                /// If this bit is set to 1, the VBUS voltage indicators from the PHY are overruled.
                ForceVbus OFFSET(10) NUMBITS(1) [],
                /// Set to one to advertise and enable USB Link Power Management support.
                LpmSup OFFSET(11) NUMBITS(1) [],
                /// Set to one to generate an interrupt when an interrupt or bulk OUT endpoint returns NAK.
                IntonnakAo OFFSET(12) NUMBITS(1) [],
                /// Set to one to generate an interrupt when an interrupt or bulk IN endpoint returns NAK.
                IntonnakAi OFFSET(13) NUMBITS(1) [],
                /// Set to one to generate an interrupt when the control OUT endpoint returns NAK.
                IntonnakCo OFFSET(14) NUMBITS(1) [],
                /// Set to one to generate an interrupt when the control IN endpoint returns NAK.
                IntonnakCi OFFSET(15) NUMBITS(1) [],
                /// Device status - connect.
                Dcon OFFSET(16) NUMBITS(1) [],
                /// Device status - suspend. Hardware supplies the status. While suspended, software writes zero to request remote wake-up; the write does not directly clear this field.
                Dsus OFFSET(17) NUMBITS(1) [],
                /// Device status - LPM Suspend. Hardware supplies the status. While LPM-suspended with remote wake-up enabled, software writes zero to request LPM remote wake-up; the write does not directly clear this field.
                LpmSus OFFSET(19) NUMBITS(1) [],
                /// LPM Remote Wake-up Enabled by USB host.
                LpmRewp OFFSET(20) NUMBITS(1) [],
                /// Set to one to suppress high-speed chirp negotiation and force full-speed operation.
                ForceFullspeed OFFSET(21) NUMBITS(1) [],
                /// This field indicates the speed at which the device operates: 00b: reserved 01b: full-speed 10b: high-speed 11b: super-speed (reserved for future use).
                Speed OFFSET(22) NUMBITS(2) [],
                /// Device status - connect change.
                DconC OFFSET(24) NUMBITS(1) [],
                /// Device status - suspend change.
                DsusC OFFSET(25) NUMBITS(1) [],
                /// Device status - reset change.
                DresC OFFSET(26) NUMBITS(1) [],
                /// Hardware sets this field when AVALID or session-end status changes. Software writes one to clear it.
                OtgC OFFSET(27) NUMBITS(1) [],
                /// This bit indicates if VBUS is detected or not.
                VbusDebounced OFFSET(28) NUMBITS(1) [],
                /// Selects the PHY test mode defined by the USB 2.0 specification.
                PhyTestMode OFFSET(29) NUMBITS(3) [],
            ],
            pub EpbufcfgT [
                /// Buffer usage: This register has one bit per physical endpoint. It is writable only when both single- and double-buffer modes are supported; double-buffer-only implementations read one and other fixed-mode implementations read zero.
                BufSb OFFSET(2) NUMBITS(14) [],
            ],
            pub EpinuseT [
                /// Reports the active buffers for EP0 OUT and EP0 IN.
                Ep0Buf OFFSET(0) NUMBITS(2) [],
                /// Buffer in use: This register has one bit per physical endpoint. Without double-buffer support these bits read zero and ignore writes.
                Buf OFFSET(2) NUMBITS(14) [],
            ],
            pub EpliststartT [
                /// Programmable portion of the USB EP Command/Status List address.
                EpListPrg OFFSET(8) NUMBITS(24) [],
            ],
            pub EpskipT [
                /// Endpoint skip: Writing 1 to one of these bits, will indicate to HW that it must deactivate the buffer assigned to this endpoint and return control back to software.
                Skip OFFSET(0) NUMBITS(16) [],
            ],
            pub EptoggleT [
                /// Endpoint data toggle: This field indicates the current value of the data toggle for the corresponding endpoint.
                Toggle OFFSET(0) NUMBITS(16) [],
            ],
            pub InfoT [
                /// Frame number.
                FrameNr OFFSET(0) NUMBITS(11) [],
                /// Reports the most recent SIE error code; software may also write this field for diagnostics.
                ErrCode OFFSET(11) NUMBITS(4) [],
                /// Minor revision.
                Minrev OFFSET(16) NUMBITS(8) [],
                /// Major revision.
                Majrev OFFSET(24) NUMBITS(8) [],
            ],
            pub IntenT [
                /// If this bit is set and the corresponding USB interrupt status bit is set, a HW interrupt is generated on the interrupt line.
                EpIntEn OFFSET(0) NUMBITS(16) [],
                /// If this bit is set and the corresponding USB interrupt status bit is set, a HW interrupt is generated on the interrupt line.
                FrameIntEn OFFSET(30) NUMBITS(1) [],
                /// If this bit is set and the corresponding USB interrupt status bit is set, a HW interrupt is generated on the interrupt line.
                DevIntEn OFFSET(31) NUMBITS(1) [],
            ],
            pub IntrouteT [
                /// Each clear bit routes the corresponding endpoint interrupt to IRQ; each set bit routes it to FIQ.
                EpIntRoute OFFSET(0) NUMBITS(16) [],
                /// Clear to route the frame interrupt to IRQ; set to route it to FIQ.
                FrameIntRoute OFFSET(30) NUMBITS(1) [],
                /// Clear to route the device-status interrupt to IRQ; set to route it to FIQ.
                DevIntRoute OFFSET(31) NUMBITS(1) [],
            ],
            pub IntstatT [
                /// Control EP0 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep0out OFFSET(0) NUMBITS(1) [],
                /// Control EP0 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep0in OFFSET(1) NUMBITS(1) [],
                /// EP1 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep1out OFFSET(2) NUMBITS(1) [],
                /// EP1 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep1in OFFSET(3) NUMBITS(1) [],
                /// EP2 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep2out OFFSET(4) NUMBITS(1) [],
                /// EP2 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep2in OFFSET(5) NUMBITS(1) [],
                /// EP3 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep3out OFFSET(6) NUMBITS(1) [],
                /// EP3 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep3in OFFSET(7) NUMBITS(1) [],
                /// EP4 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep4out OFFSET(8) NUMBITS(1) [],
                /// EP4 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep4in OFFSET(9) NUMBITS(1) [],
                /// EP5 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep5out OFFSET(10) NUMBITS(1) [],
                /// EP5 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep5in OFFSET(11) NUMBITS(1) [],
                /// Interrupt status for configured physical endpoints above EP5. Write one through INTSTAT to clear or through INTSETSTAT to set.
                EpUpper OFFSET(12) NUMBITS(4) [],
                /// Frame interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                FrameInt OFFSET(30) NUMBITS(1) [],
                /// Device interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                DevInt OFFSET(31) NUMBITS(1) [],
            ],
            pub LpmT [
                /// Host Initiated Resume Duration - HW.
                HirdHw OFFSET(0) NUMBITS(4) [],
                /// Host Initiated Resume Duration - SW.
                HirdSw OFFSET(4) NUMBITS(4) [],
                /// As long as this bit is set to one and LPM supported bit is set to one, HW will return a NYET handshake on every LPM token it receives.
                DataPending OFFSET(8) NUMBITS(1) [],
                /// Set to one to disable the external VBUS comparator.
                VbuscompOff OFFSET(16) NUMBITS(1) [],
                /// Controls the PHY VBUS-charge output.
                ChrgVbus OFFSET(17) NUMBITS(1) [],
                /// Controls the PHY VBUS-discharge output.
                DischrgVbus OFFSET(18) NUMBITS(1) [],
                /// Reports the synchronized PHY AVALID indication.
                Avalid OFFSET(20) NUMBITS(1) [],
                /// Reports the synchronized PHY session-end indication.
                Sessend OFFSET(21) NUMBITS(1) [],
            ],
            pub UlpidebugT [
                /// In ULPI mode, the low nibble of the PHY register address. In UTMI+ mode, drives VControl.
                PhyAddr OFFSET(0) NUMBITS(4) [],
                /// Upper nibble of the ULPI PHY register address. Without ULPI support, reads zero and ignores writes.
                PhyAddrHigh OFFSET(4) NUMBITS(4) [],
                /// Provides write data for a ULPI PHY-register transaction. Without ULPI support, reads zero and ignores writes.
                PhyWdata OFFSET(8) NUMBITS(8) [],
                /// Reports ULPI PHY-register read data or the UTMI+ VStatus value.
                PhyRdata OFFSET(16) NUMBITS(8) [],
                /// Selects a ULPI write when set and a ULPI read when clear. Without ULPI support, reads zero and ignores writes.
                PhyRw OFFSET(24) NUMBITS(1) [],
                /// Software writes this bit to one to start a read or write operation. Hardware clears it when the PHY transaction completes.
                PhyAccess OFFSET(25) NUMBITS(1) [],
                /// Selects the PHY interface when both UTMI+ and ULPI are supported. With only one interface, this field reports the fixed mode and ignores writes.
                PhyMode OFFSET(31) NUMBITS(1) [],
            ],
    }
}
pub mod regs {
    //! Types that represent registers.
    use tock_registers::register_structs;
    register_structs! {
        pub UsbDev1 {
            (0x0 => pub devcmdstat: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::DevcmdstatT::Register>),
            (0x4 => pub info: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::InfoT::Register>),
            (0x8 => pub epliststart: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::EpliststartT::Register>),
            (0xc => pub databufstart: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::DatabufstartT::Register>),
            (0x10 => pub lpm: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::LpmT::Register>),
            (0x14 => pub epskip: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::EpskipT::Register>),
            (0x18 => pub epinuse: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::EpinuseT::Register>),
            (0x1c => pub epbufcfg: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::EpbufcfgT::Register>),
            (0x20 => pub intstat: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::IntstatT::Register>),
            (0x24 => pub inten: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::IntenT::Register>),
            (0x28 => pub intsetstat: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::Intsetstat::Register>),
            (0x2c => pub introute: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::IntrouteT::Register>),
            (0x30 => pub config: tock_registers::registers::ReadOnly<u32, crate::usb_dev1::bits::ConfigT::Register>),
            (0x34 => pub eptoggle: tock_registers::registers::ReadOnly<u32, crate::usb_dev1::bits::EptoggleT::Register>),
            (0x38 => pub clkctrl: tock_registers::registers::ReadOnly<u32, crate::usb_dev1::bits::ClkctrlT::Register>),
            (0x3c => pub ulpidebug: tock_registers::registers::ReadWrite<u32, crate::usb_dev1::bits::UlpidebugT::Register>),
            (0x40 => @END),
        }
    }
}
