// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at dfa6c631dbfc00c8e0c7e6b256619d03d74f0bdc
//
pub const USB_COMBO_ADDR: u32 = 0x2000_0000;
pub mod bits {
    //! Types that represent individual registers (bitfields).
    use tock_registers::register_bitfields;
    register_bitfields! {
        u32,
            pub CaliptraCtrl [
                /// Emergency-fallback control bit. When set, forces the VHDL post-synchronizer OCP recovery arbiter (usb_ocp_recovery_post_sync_arb.m.vhdl, ocp_path_disable_i port) to never claim an OCP-class SETUP, so every EP0 transfer falls through to the legacy SIE / MCU EPCS path bit-identically to the un-arbitered IP. Firmware/EXT write-only (swwe gated by rb_is_ext in usb_ocp_recovery_top.sv), so a USB-host write is ignored. Reset default 0 (OCP recovery path active).
                OcpPathDisable OFFSET(0) NUMBITS(1) [],
                /// Firmware-only write-one request that atomically aborts an in-flight OCP recovery claim. Hardware consumes the request and clears the stored bit after one cycle. This is distinct from OCP_PATH_DISABLE, which persistently disables future OCP claims.
                OcpClaimAbort OFFSET(1) NUMBITS(1) [],
                /// Firmware-only write-one request to report OCP_PROTOCOL_ERROR_GENERAL (0xFF) after an interrupted FIFO DATA batch. Hardware accepts the request only while CALIPTRA_STATUS.BATCH_ABORTED is asserted, enters persistent USB protocol STALL, and clears this stored request after one cycle.
                OcpProtocolErrorGeneral OFFSET(2) NUMBITS(1) [],
                /// Reserved for future Caliptra-specific control bits.
                Reserved313 OFFSET(3) NUMBITS(29) [],
            ],
            pub CaliptraStatus [
                /// Sticky: set when an INDIRECT_FIFO_CTRL region reset occurs; cleared on the next region reset. Driven by usb_ocp_recovery_cms_fifo.sv region_reset_q.
                RegionReset OFFSET(0) NUMBITS(1) [],
                /// Sticky: set on a genuine FIFO-full overflow drop while the image is still incomplete. Driven by usb_ocp_recovery_cms_fifo.sv overflow_q.
                Overflow OFFSET(1) NUMBITS(1) [],
                /// Sticky: set when the pushed DWORD count reaches the programmed image size. Driven by usb_ocp_recovery_cms_fifo.sv image_done_q.
                ImageDone OFFSET(2) NUMBITS(1) [],
                /// Sticky: set when a new EP0 SETUP aborts a claimed INDIRECT_FIFO_DATA OUT transfer and flushes the unconsumed batch. Cleared by an INDIRECT_FIFO_CTRL reset.
                BatchAborted OFFSET(3) NUMBITS(1) [],
                /// Reserved for future Caliptra-specific status bits.
                Reserved314 OFFSET(4) NUMBITS(28) [],
            ],
            pub Control [
                /// Set to one to select the HUB as the upstream USB device and enable HUB-specific device and port routing. When zero, the upstream connection path uses Device 0 instead. The synchronized USB_EnableHub input continuously forces this field and DCON to one while asserted. This field remains software-writable while the table lock is active.
                Enable OFFSET(0) NUMBITS(1) [],
                /// Stored and read back by the register interface but unused by HUB logic. Software should write zero.
                ReservedLow OFFSET(1) NUMBITS(15) [],
                /// Requests connection of the HUB device to the upstream USB bus. The effective HUB connection is DCON qualified by synchronized debounced VBUS and is selected upstream when ENABLE is one. The synchronized USB_EnableHub input continuously forces this field and ENABLE to one while asserted. This field remains software-writable while the table lock is active.
                Dcon OFFSET(16) NUMBITS(1) [],
                /// Stored and read back by the register interface but unused by HUB logic. Software should write zero.
                Reserved17 OFFSET(17) NUMBITS(1) [],
                /// Selects self-powered reporting when set. The effective self-powered state is this field OR the synchronized USB_self_powered pin. A change in the effective state overwrites the bmAttributes byte in table word 17 with 0xC0 for self-powered or 0x80 for bus-powered and, for the high-speed configuration, applies the same overwrite to table word 65. Other software-programmed bits in those bytes are not preserved across the update. The output consumed by HUB request handling is the registered effective state.
                SelfPowered OFFSET(18) NUMBITS(1) [],
                /// Stored and read back by the register interface but unused by HUB logic. Software should write zero.
                ReservedHigh OFFSET(19) NUMBITS(13) [],
            ],
            pub DeviceId0 [
                /// Byte 0 selects the DEVICE_ID encoding such as PCI, IANA, UUID, PnP, ACPI, or NVMe-MI. OCP Recovery v1.1 Sec 9.2 DEVICE_ID.
                DescType OFFSET(0) NUMBITS(8) [],
                /// Byte 1 reports the optional vendor string length. OCP Recovery v1.1 Sec 9.2 DEVICE_ID.
                VendorSpecificStrLength OFFSET(8) NUMBITS(8) [],
                /// Bytes 2-3 hold the first descriptor-specific payload bytes for the selected DEVICE_ID type. OCP Recovery v1.1 Sec 9.2 DEVICE_ID.
                Data32 OFFSET(16) NUMBITS(16) [],
            ],
            pub DeviceReset [
                /// Byte 0 requests device reset or management reset. USB Recovery Agent writes use the hardware interface; firmware can read or clear the request through cpuif.
                ResetCtrl OFFSET(0) NUMBITS(8) [],
                /// Byte 1 controls forced recovery or flashless boot on the next platform reset (0xE = enter flashless boot mode, 0xF = enter recovery mode). OCP Recovery v1.1 Sec 9.2 DEVICE_RESET.
                ForcedRecovery OFFSET(8) NUMBITS(8) [],
                /// Byte 2 controls interface mastering enable. OCP Recovery v1.1 Sec 9.2 DEVICE_RESET.
                IfCtrl OFFSET(16) NUMBITS(8) [],
                /// Byte 3 is padding introduced by the DWORD-aligned RDL view and is not part of the OCP Recovery DEVICE_RESET command payload (OCP Recovery v1.1 Sec 9.2 DEVICE_RESET is 3 bytes). Matches the clean reserved byte-3 pattern of RECOVERY_CTRL.
                Reserved3124 OFFSET(24) NUMBITS(8) [],
            ],
            pub DeviceStatus0 [
                /// Byte 0 reports device health and recovery state. Firmware owns the stored value through cpuif; the USB Recovery Agent reads the same value. OCP Recovery v1.1 Sec 9.2 DEVICE_STATUS.
                DevStatus OFFSET(0) NUMBITS(8) [],
                /// Byte 1 reports protocol error. OCP Recovery v1.1 Sec 9.2 defines clear-on-read for the Recovery Agent USB command; the control-transfer decoder performs that clear after a completed USB DEVICE_STATUS read. Internal firmware reads do not clear the field.
                ProtError OFFSET(8) NUMBITS(8) [],
                /// Bytes 2-3 report the 16-bit recovery reason code. Firmware owns the stored value through cpuif; the USB Recovery Agent reads the same value. OCP Recovery v1.1 Sec 9.2 DEVICE_STATUS and Table 3.
                RecReasonCode OFFSET(16) NUMBITS(16) [],
            ],
            pub DeviceStatus1 [
                /// Bytes 4-5 hold the heartbeat counter. OCP Recovery v1.1 Sec 9.2 DEVICE_STATUS.
                Heartbeat OFFSET(0) NUMBITS(16) [],
                /// Byte 6 reports the vendor status payload length. OCP Recovery v1.1 Sec 9.2 DEVICE_STATUS.
                VendorStatusLength OFFSET(16) NUMBITS(8) [],
                /// Byte 7 is the first byte of VENDOR_STATUS. OCP Recovery v1.1 Sec 9.2 DEVICE_STATUS.
                VendorStatus0 OFFSET(24) NUMBITS(8) [],
            ],
            pub HwStatus [
                /// Byte 0 bit 0 reports temperature-critical status. Firmware owns the stored byte through cpuif and the USB Recovery Agent reads the same storage. OCP Recovery v1.1 Sec 9.2 HW_STATUS.
                TempCritical OFFSET(0) NUMBITS(1) [],
                /// Byte 0 bit 1 reports a hardware soft error. Firmware owns the stored byte through cpuif and the USB Recovery Agent reads the same storage. OCP Recovery v1.1 Sec 9.2 HW_STATUS.
                SoftErr OFFSET(1) NUMBITS(1) [],
                /// Byte 0 bit 2 reports a hardware fatal error. Firmware owns the stored byte through cpuif and the USB Recovery Agent reads the same storage. OCP Recovery v1.1 Sec 9.2 HW_STATUS.
                FatalErr OFFSET(2) NUMBITS(1) [],
                /// Byte 0 bits 7:3 are reserved. Firmware owns the stored byte through cpuif and the USB Recovery Agent reads the same storage. OCP Recovery v1.1 Sec 9.2 HW_STATUS.
                Reserved73 OFFSET(3) NUMBITS(5) [],
                /// Byte 1 holds the vendor HW status bitmap. Firmware owns the stored byte through cpuif and the USB Recovery Agent reads the same storage. This byte location matches the corrected usb_ocp_recovery_reg.sv layout and OCP Recovery v1.1 Sec 9.2 HW_STATUS.
                VendorHwStatus OFFSET(8) NUMBITS(8) [],
                /// Byte 2 reports composite temperature. Firmware owns the stored byte through cpuif and the USB Recovery Agent reads the same storage. OCP Recovery v1.1 Sec 9.2 HW_STATUS.
                Ctemp OFFSET(16) NUMBITS(8) [],
                /// Byte 3 reports the vendor HW status payload length. Firmware owns the stored byte through cpuif and the USB Recovery Agent reads the same storage. This byte location matches the corrected usb_ocp_recovery_reg.sv layout and OCP Recovery v1.1 Sec 9.2 HW_STATUS.
                VendorHwStatusLen OFFSET(24) NUMBITS(8) [],
            ],
            pub IndirectFifoCtrl0 [
                /// Byte 0 selects the FIFO-backed component memory space. Firmware accesses route through cpuif, while usb_ocp_recovery_cms_fifo.sv remains the live owner and mirrors the committed state back through hw=w. OCP Recovery v1.1 Sec 9.2 INDIRECT_FIFO_CTRL command summary.
                Cms OFFSET(0) NUMBITS(8) [],
                /// Byte 1 bit 0 requests FIFO reset and the device clears it after use (write 1 to reset the indices). Firmware accesses route through cpuif, while usb_ocp_recovery_cms_fifo.sv remains the live owner and mirrors the committed state back through hw=w. OCP Recovery v1.1 Sec 9.2 INDIRECT_FIFO_CTRL command summary.
                Reset OFFSET(8) NUMBITS(8) [],
                /// Bytes 2-3 are reserved.
                Reserved3116 OFFSET(16) NUMBITS(16) [],
            ],
            pub IndirectFifoStatus0 [
                /// Byte 0 bit 0 indicates the FIFO is empty. OCP Recovery v1.1 Sec 9.2 INDIRECT_FIFO_STATUS command summary.
                Empty OFFSET(0) NUMBITS(1) [],
                /// Byte 0 bit 1 indicates the FIFO is full. OCP Recovery v1.1 Sec 9.2 INDIRECT_FIFO_STATUS command summary.
                Full OFFSET(1) NUMBITS(1) [],
                /// Byte 0 bits 7:2 are reserved in the OCP Recovery INDIRECT_FIFO_STATUS command (Sec 9.2 defines only bit 0 empty and bit 1 full). Caliptra-specific FIFO status (region reset / overflow / image done) lives in the CALIPTRA_STATUS register outside the OCP command aperture.
                Reserved72 OFFSET(2) NUMBITS(6) [],
                /// Byte 1 reports the selected FIFO region type. The current USB implementation returns 0x00 for code space. OCP Recovery v1.1 Sec 9.2 INDIRECT_FIFO_STATUS command summary and usb_ocp_recovery_cms_fifo.sv.
                RegionType OFFSET(8) NUMBITS(8) [],
                /// Bytes 2-3 are reserved. OCP Recovery v1.1 Sec 9.2 INDIRECT_FIFO_STATUS command summary.
                Reserved3116 OFFSET(16) NUMBITS(16) [],
            ],
            pub Intsetstat [
                EpSetInt OFFSET(0) NUMBITS(16) [],
                FrameSetInt OFFSET(30) NUMBITS(1) [],
                DevSetInt OFFSET(31) NUMBITS(1) [],
            ],
            pub ProtCap2 [
                /// Bytes 8-9 encode major=1 and minor=1 for OCP Recovery v1.1. OCP Recovery v1.1 Sec 9.2 PROT_CAP. Static read-only constant: the RDL reset is the single source of truth (no hw drive).
                RecProtVersion OFFSET(0) NUMBITS(16) [],
                /// AGENT_CAPS bit 0: Identification (DEVICE_ID structure). OCP Recovery v1.1 Sec 9.2 PROT_CAP. Reset 1. Firmware-configurable (sw=rw); the USB host is RO -- a host write to PROT_CAP raises PROTOCOL_ERROR (Sec 9.1, source-qualified via rb_is_ext in usb_ocp_recovery_rb_adapter.sv).
                AgentCapsIdentification OFFSET(16) NUMBITS(1) [],
                /// AGENT_CAPS bit 1: Forced Recovery (from RESET). OCP Recovery v1.1 Sec 9.2 PROT_CAP. Reset 1. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsForcedRecovery OFFSET(17) NUMBITS(1) [],
                /// AGENT_CAPS bit 2: Mgmt reset (from RESET). OCP Recovery v1.1 Sec 9.2 PROT_CAP. Not supported; reset 0. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsMgmtReset OFFSET(18) NUMBITS(1) [],
                /// AGENT_CAPS bit 3: Device Reset (from RESET). OCP Recovery v1.1 Sec 9.2 PROT_CAP. Reset 1. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsDeviceReset OFFSET(19) NUMBITS(1) [],
                /// AGENT_CAPS bit 4: Device status (DEVICE_STATUS). OCP Recovery v1.1 Sec 9.2 PROT_CAP. Reset 1. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsDeviceStatus OFFSET(20) NUMBITS(1) [],
                /// AGENT_CAPS bit 5: Recovery memory access (direct CMS-memory window via INDIRECT_CTRL/STATUS/DATA, OCP commands 0x29/0x2A/0x2B). This agent is FIFO-only; the direct memory window is NOT implemented (the direct CMS-memory window register definitions were removed). Reset 0. OCP Recovery v1.1 Sec 9.2 PROT_CAP. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsRecoveryMemAccess OFFSET(21) NUMBITS(1) [],
                /// AGENT_CAPS bit 6: Local C-image support. OCP Recovery v1.1 Sec 9.2 PROT_CAP. Not supported; reset 0. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsLocalCImage OFFSET(22) NUMBITS(1) [],
                /// AGENT_CAPS bit 7: Push C-image support (FIFO streaming boot). OCP Recovery v1.1 Sec 9.2 PROT_CAP. Reset 1. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsPushCImage OFFSET(23) NUMBITS(1) [],
                /// AGENT_CAPS bit 8: Interface isolation. OCP Recovery v1.1 Sec 9.2 PROT_CAP. Not supported; reset 0. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsInterfaceIsolation OFFSET(24) NUMBITS(1) [],
                /// AGENT_CAPS bit 9: Hardware status (HW_STATUS). OCP Recovery v1.1 Sec 9.2 PROT_CAP. Reset 1. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsHardwareStatus OFFSET(25) NUMBITS(1) [],
                /// AGENT_CAPS bit 10: Vendor command (VENDOR). OCP Recovery v1.1 Sec 9.2 PROT_CAP. Reset 1. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsVendorCommand OFFSET(26) NUMBITS(1) [],
                /// AGENT_CAPS bit 11: Flashless boot (from RESET). OCP Recovery v1.1 Sec 9.2 PROT_CAP. Advertised 1: this design supports flashless boot (host writes DEVICE_RESET.FORCED_RECOVERY=0xE to enter flashless boot on the next platform reset). Firmware-configurable (sw=rw), reset default 1; the USB host is RO -- a host write to PROT_CAP raises PROTOCOL_ERROR (Sec 9.1). Sets AGENT_CAPS = 0x1E9B.
                AgentCapsFlashlessBoot OFFSET(27) NUMBITS(1) [],
                /// AGENT_CAPS bit 12: FIFO CMS support (INDIRECT_FIFO_CTRL). OCP Recovery v1.1 Sec 9.2 PROT_CAP. Reset 1. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                AgentCapsFifoCmsSupport OFFSET(28) NUMBITS(1) [],
                /// AGENT_CAPS bits 13-15: reserved. OCP Recovery v1.1 Sec 9.2 PROT_CAP. Reset 0.
                AgentCapsReserved OFFSET(29) NUMBITS(3) [],
            ],
            pub ProtCap3 [
                /// Byte 12 reports the number of component memory spaces. Advertises one CMS region: after the direct CMS-memory window (INDIRECT_CTRL/STATUS/DATA) was removed, only the FIFO-backed CMS region remains (OCP Recovery v1.1 Sec 9.2 PROT_CAP; this count includes logging, code and vendor regions). Firmware-configurable (sw=rw), reset default 1; the USB host is RO -- a host write to PROT_CAP raises PROTOCOL_ERROR (Sec 9.1).
                NumOfCmsRegions OFFSET(0) NUMBITS(8) [],
                /// Byte 13 reports maximum response time in 2^x microseconds. OCP Recovery v1.1 Sec 9.2 PROT_CAP. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                MaxRespTime OFFSET(8) NUMBITS(8) [],
                /// Byte 14 reports heartbeat period in 2^x microseconds, with 0 meaning not supported. OCP Recovery v1.1 Sec 9.2 PROT_CAP. Firmware-configurable (sw=rw); host writes raise PROTOCOL_ERROR.
                HeartbeatPeriod OFFSET(16) NUMBITS(8) [],
                /// Byte 15 is reserved. OCP Recovery v1.1 Sec 9.2 PROT_CAP. Static read-only constant (sw=r; hw=na).
                Reserved3124 OFFSET(24) NUMBITS(8) [],
            ],
            pub RecoveryCtrl [
                /// Byte 0 selects the component memory space containing the recovery image. USB Recovery Agent writes use the hardware interface. OCP Recovery v1.1 Sec 9.2 RECOVERY_CTRL.
                Cms OFFSET(0) NUMBITS(8) [],
                /// Byte 1 selects memory-window or device-stored recovery image source. USB Recovery Agent writes use the hardware interface. OCP Recovery v1.1 Sec 9.2 RECOVERY_CTRL.
                RecImgSel OFFSET(8) NUMBITS(8) [],
                /// Byte 2 requests activation of the selected recovery image. The USB Recovery Agent writes 0x0F through the hardware interface; firmware can clear the stored request through cpuif after device handling. OCP Recovery v1.1 Sec 9.2 RECOVERY_CTRL.
                ActivateRecImg OFFSET(16) NUMBITS(8) [],
                /// Byte 3 is padding introduced by the DWORD-aligned RDL view and is not part of the OCP command payload.
                Reserved3124 OFFSET(24) NUMBITS(8) [],
            ],
            pub RecoveryStatus [
                /// Byte 0 bits 3:0 report recovery status. Firmware owns the stored value through cpuif; the USB Recovery Agent reads the same value. OCP Recovery v1.1 Sec 9.2 RECOVERY_STATUS.
                DevRecStatus OFFSET(0) NUMBITS(4) [],
                /// Byte 0 bits 7:4 report the recovery image index. Firmware owns the stored value through cpuif; the USB Recovery Agent reads the same value. OCP Recovery v1.1 Sec 9.2 RECOVERY_STATUS.
                RecImgIndex OFFSET(4) NUMBITS(4) [],
                /// Byte 1 reports vendor-specific recovery status. Firmware owns the stored value through cpuif; the USB Recovery Agent reads the same value. OCP Recovery v1.1 Sec 9.2 RECOVERY_STATUS.
                VendorSpecificStatus OFFSET(8) NUMBITS(8) [],
                /// Bytes 2-3 are padding introduced by the DWORD-aligned RDL view and are not part of the OCP command payload.
                Reserved3116 OFFSET(16) NUMBITS(16) [],
            ],
            pub Vendor [
                /// Byte 0 placeholder for the vendor-defined command space. This project currently models only one byte, reset to 0. OCP Recovery v1.1 Sec 9.2 VENDOR command summary.
                VendorData OFFSET(0) NUMBITS(8) [],
                /// Bytes 1-3 are padding introduced by the DWORD-aligned RDL view and are not part of the current placeholder payload.
                Reserved318 OFFSET(8) NUMBITS(24) [],
            ],
            pub ClkctrlT [
                /// Set to one to select the external USB clock. When PLL support is absent, this field reads one and ignores writes.
                ExtClkEnable OFFSET(0) NUMBITS(1) [],
            ],
            pub ConfigT [
                /// Reports the configured number of physical endpoints above the two EP0 directions.
                Nbphysep OFFSET(0) NUMBITS(5) [],
                /// Reports whether single-buffer endpoint operation is implemented.
                SingleBuffer OFFSET(5) NUMBITS(1) [],
                /// Reports whether double-buffer endpoint operation is implemented.
                DoubleBuffer OFFSET(6) NUMBITS(1) [],
                /// Reports whether endpoint data-toggle state is readable through EPTOGGLE.
                ToggleReadable OFFSET(7) NUMBITS(1) [],
                /// Reports whether the controller includes programmable PLL clock control.
                Pll OFFSET(8) NUMBITS(1) [],
                /// Reports whether the UTMI+ PHY interface is implemented.
                Utmi OFFSET(9) NUMBITS(1) [],
                /// Reports whether the ULPI PHY interface is implemented.
                Ulpi OFFSET(10) NUMBITS(1) [],
            ],
            pub DatabufstartT [
                /// Programmable portion of the start address for the endpoint data-buffer area.
                DaBuf OFFSET(17) NUMBITS(15) [],
            ],
            pub DevcmdstatT [
                /// USB device address. Software writes update a pending address used during SET_ADDRESS processing; software reads return the committed address. Hardware commits the pending address when the SET_ADDRESS status stage completes.
                DevAddr OFFSET(0) NUMBITS(7) [],
                /// USB device enable.
                DevEn OFFSET(7) NUMBITS(1) [],
                /// SETUP token received.
                Setup OFFSET(8) NUMBITS(1) [],
                /// Set to one to force the NEEDCLK indication active.
                ForceNeedclk OFFSET(9) NUMBITS(1) [],
                /// If this bit is set to 1, the VBUS voltage indicators from the PHY are overruled.
                ForceVbus OFFSET(10) NUMBITS(1) [],
                /// Set to one to advertise and enable USB Link Power Management support.
                LpmSup OFFSET(11) NUMBITS(1) [],
                /// Set to one to generate an interrupt when an interrupt or bulk OUT endpoint returns NAK.
                IntonnakAo OFFSET(12) NUMBITS(1) [],
                /// Set to one to generate an interrupt when an interrupt or bulk IN endpoint returns NAK.
                IntonnakAi OFFSET(13) NUMBITS(1) [],
                /// Set to one to generate an interrupt when the control OUT endpoint returns NAK.
                IntonnakCo OFFSET(14) NUMBITS(1) [],
                /// Set to one to generate an interrupt when the control IN endpoint returns NAK.
                IntonnakCi OFFSET(15) NUMBITS(1) [],
                /// Device status - connect.
                Dcon OFFSET(16) NUMBITS(1) [],
                /// Device status - suspend. Hardware supplies the status. While suspended, software writes zero to request remote wake-up; the write does not directly clear this field.
                Dsus OFFSET(17) NUMBITS(1) [],
                /// Device status - LPM Suspend. Hardware supplies the status. While LPM-suspended with remote wake-up enabled, software writes zero to request LPM remote wake-up; the write does not directly clear this field.
                LpmSus OFFSET(19) NUMBITS(1) [],
                /// LPM Remote Wake-up Enabled by USB host.
                LpmRewp OFFSET(20) NUMBITS(1) [],
                /// Set to one to suppress high-speed chirp negotiation and force full-speed operation.
                ForceFullspeed OFFSET(21) NUMBITS(1) [],
                /// This field indicates the speed at which the device operates: 00b: reserved 01b: full-speed 10b: high-speed 11b: super-speed (reserved for future use).
                Speed OFFSET(22) NUMBITS(2) [],
                /// Device status - connect change.
                DconC OFFSET(24) NUMBITS(1) [],
                /// Device status - suspend change.
                DsusC OFFSET(25) NUMBITS(1) [],
                /// Device status - reset change.
                DresC OFFSET(26) NUMBITS(1) [],
                /// Hardware sets this field when AVALID or session-end status changes. Software writes one to clear it.
                OtgC OFFSET(27) NUMBITS(1) [],
                /// This bit indicates if VBUS is detected or not.
                VbusDebounced OFFSET(28) NUMBITS(1) [],
                /// Selects the PHY test mode defined by the USB 2.0 specification.
                PhyTestMode OFFSET(29) NUMBITS(3) [],
            ],
            pub EpbufcfgT [
                /// Buffer usage: This register has one bit per physical endpoint. It is writable only when both single- and double-buffer modes are supported; double-buffer-only implementations read one and other fixed-mode implementations read zero.
                BufSb OFFSET(2) NUMBITS(14) [],
            ],
            pub EpinuseT [
                /// Reports the active buffers for EP0 OUT and EP0 IN.
                Ep0Buf OFFSET(0) NUMBITS(2) [],
                /// Buffer in use: This register has one bit per physical endpoint. Without double-buffer support these bits read zero and ignore writes.
                Buf OFFSET(2) NUMBITS(14) [],
            ],
            pub EpliststartT [
                /// Programmable portion of the USB EP Command/Status List address.
                EpListPrg OFFSET(8) NUMBITS(24) [],
            ],
            pub EpskipT [
                /// Endpoint skip: Writing 1 to one of these bits, will indicate to HW that it must deactivate the buffer assigned to this endpoint and return control back to software.
                Skip OFFSET(0) NUMBITS(16) [],
            ],
            pub EptoggleT [
                /// Endpoint data toggle: This field indicates the current value of the data toggle for the corresponding endpoint.
                Toggle OFFSET(0) NUMBITS(16) [],
            ],
            pub InfoT [
                /// Frame number.
                FrameNr OFFSET(0) NUMBITS(11) [],
                /// Reports the most recent SIE error code; software may also write this field for diagnostics.
                ErrCode OFFSET(11) NUMBITS(4) [],
                /// Minor revision.
                Minrev OFFSET(16) NUMBITS(8) [],
                /// Major revision.
                Majrev OFFSET(24) NUMBITS(8) [],
            ],
            pub IntenT [
                /// If this bit is set and the corresponding USB interrupt status bit is set, a HW interrupt is generated on the interrupt line.
                EpIntEn OFFSET(0) NUMBITS(16) [],
                /// If this bit is set and the corresponding USB interrupt status bit is set, a HW interrupt is generated on the interrupt line.
                FrameIntEn OFFSET(30) NUMBITS(1) [],
                /// If this bit is set and the corresponding USB interrupt status bit is set, a HW interrupt is generated on the interrupt line.
                DevIntEn OFFSET(31) NUMBITS(1) [],
            ],
            pub IntrouteT [
                /// Each clear bit routes the corresponding endpoint interrupt to IRQ; each set bit routes it to FIQ.
                EpIntRoute OFFSET(0) NUMBITS(16) [],
                /// Clear to route the frame interrupt to IRQ; set to route it to FIQ.
                FrameIntRoute OFFSET(30) NUMBITS(1) [],
                /// Clear to route the device-status interrupt to IRQ; set to route it to FIQ.
                DevIntRoute OFFSET(31) NUMBITS(1) [],
            ],
            pub IntstatT [
                /// Control EP0 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep0out OFFSET(0) NUMBITS(1) [],
                /// Control EP0 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep0in OFFSET(1) NUMBITS(1) [],
                /// EP1 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep1out OFFSET(2) NUMBITS(1) [],
                /// EP1 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep1in OFFSET(3) NUMBITS(1) [],
                /// EP2 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep2out OFFSET(4) NUMBITS(1) [],
                /// EP2 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep2in OFFSET(5) NUMBITS(1) [],
                /// EP3 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep3out OFFSET(6) NUMBITS(1) [],
                /// EP3 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep3in OFFSET(7) NUMBITS(1) [],
                /// EP4 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep4out OFFSET(8) NUMBITS(1) [],
                /// EP4 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep4in OFFSET(9) NUMBITS(1) [],
                /// EP5 OUT interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep5out OFFSET(10) NUMBITS(1) [],
                /// EP5 IN interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                Ep5in OFFSET(11) NUMBITS(1) [],
                /// Interrupt status for configured physical endpoints above EP5. Write one through INTSTAT to clear or through INTSETSTAT to set.
                EpUpper OFFSET(12) NUMBITS(4) [],
                /// Frame interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                FrameInt OFFSET(30) NUMBITS(1) [],
                /// Device interrupt status. Write one through INTSTAT to clear or through INTSETSTAT to set.
                DevInt OFFSET(31) NUMBITS(1) [],
            ],
            pub LpmT [
                /// Host Initiated Resume Duration - HW.
                HirdHw OFFSET(0) NUMBITS(4) [],
                /// Host Initiated Resume Duration - SW.
                HirdSw OFFSET(4) NUMBITS(4) [],
                /// As long as this bit is set to one and LPM supported bit is set to one, HW will return a NYET handshake on every LPM token it receives.
                DataPending OFFSET(8) NUMBITS(1) [],
                /// Set to one to disable the external VBUS comparator.
                VbuscompOff OFFSET(16) NUMBITS(1) [],
                /// Controls the PHY VBUS-charge output.
                ChrgVbus OFFSET(17) NUMBITS(1) [],
                /// Controls the PHY VBUS-discharge output.
                DischrgVbus OFFSET(18) NUMBITS(1) [],
                /// Reports the synchronized PHY AVALID indication.
                Avalid OFFSET(20) NUMBITS(1) [],
                /// Reports the synchronized PHY session-end indication.
                Sessend OFFSET(21) NUMBITS(1) [],
            ],
            pub UlpidebugT [
                /// In ULPI mode, the low nibble of the PHY register address. In UTMI+ mode, drives VControl.
                PhyAddr OFFSET(0) NUMBITS(4) [],
                /// Upper nibble of the ULPI PHY register address. Without ULPI support, reads zero and ignores writes.
                PhyAddrHigh OFFSET(4) NUMBITS(4) [],
                /// Provides write data for a ULPI PHY-register transaction. Without ULPI support, reads zero and ignores writes.
                PhyWdata OFFSET(8) NUMBITS(8) [],
                /// Reports ULPI PHY-register read data or the UTMI+ VStatus value.
                PhyRdata OFFSET(16) NUMBITS(8) [],
                /// Selects a ULPI write when set and a ULPI read when clear. Without ULPI support, reads zero and ignores writes.
                PhyRw OFFSET(24) NUMBITS(1) [],
                /// Software writes this bit to one to start a read or write operation. Hardware clears it when the PHY transaction completes.
                PhyAccess OFFSET(25) NUMBITS(1) [],
                /// Selects the PHY interface when both UTMI+ and ULPI are supported. With only one interface, this field reports the fixed mode and ignores writes.
                PhyMode OFFSET(31) NUMBITS(1) [],
            ],
    }
}
pub mod regs {
    //! Types that represent registers.
    use tock_registers::register_structs;
    register_structs! {
        pub UsbCombo {
            (0x0 => pub dev0_csr_devcmdstat: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::DevcmdstatT::Register>),
            (0x4 => pub dev0_csr_info: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::InfoT::Register>),
            (0x8 => pub dev0_csr_epliststart: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::EpliststartT::Register>),
            (0xc => pub dev0_csr_databufstart: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::DatabufstartT::Register>),
            (0x10 => pub dev0_csr_lpm: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::LpmT::Register>),
            (0x14 => pub dev0_csr_epskip: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::EpskipT::Register>),
            (0x18 => pub dev0_csr_epinuse: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::EpinuseT::Register>),
            (0x1c => pub dev0_csr_epbufcfg: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::EpbufcfgT::Register>),
            (0x20 => pub dev0_csr_intstat: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::IntstatT::Register>),
            (0x24 => pub dev0_csr_inten: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::IntenT::Register>),
            (0x28 => pub dev0_csr_intsetstat: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::Intsetstat::Register>),
            (0x2c => pub dev0_csr_introute: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::IntrouteT::Register>),
            (0x30 => pub dev0_csr_config: tock_registers::registers::ReadOnly<u32, crate::usb_combo::bits::ConfigT::Register>),
            (0x34 => pub dev0_csr_eptoggle: tock_registers::registers::ReadOnly<u32, crate::usb_combo::bits::EptoggleT::Register>),
            (0x38 => pub dev0_csr_clkctrl: tock_registers::registers::ReadOnly<u32, crate::usb_combo::bits::ClkctrlT::Register>),
            (0x3c => pub dev0_csr_ulpidebug: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::UlpidebugT::Register>),
            (0x40 => _reserved0),
            (0x800 => pub recovery_prot_cap_0: tock_registers::registers::ReadOnly<u32>),
            (0x804 => pub recovery_prot_cap_1: tock_registers::registers::ReadOnly<u32>),
            (0x808 => pub recovery_prot_cap_2: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::ProtCap2::Register>),
            (0x80c => pub recovery_prot_cap_3: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::ProtCap3::Register>),
            (0x810 => pub recovery_device_id_0: tock_registers::registers::ReadOnly<u32, crate::usb_combo::bits::DeviceId0::Register>),
            (0x814 => pub recovery_device_id_1: tock_registers::registers::ReadOnly<u32>),
            (0x818 => pub recovery_device_id_2: tock_registers::registers::ReadOnly<u32>),
            (0x81c => pub recovery_device_id_3: tock_registers::registers::ReadOnly<u32>),
            (0x820 => pub recovery_device_id_4: tock_registers::registers::ReadOnly<u32>),
            (0x824 => pub recovery_device_id_5: tock_registers::registers::ReadOnly<u32>),
            (0x828 => pub recovery_device_status_0: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::DeviceStatus0::Register>),
            (0x82c => pub recovery_device_status_1: tock_registers::registers::ReadOnly<u32, crate::usb_combo::bits::DeviceStatus1::Register>),
            (0x830 => pub recovery_device_status_2: tock_registers::registers::ReadOnly<u32>),
            (0x834 => pub recovery_device_status_3: tock_registers::registers::ReadOnly<u32>),
            (0x838 => pub recovery_device_status_4: tock_registers::registers::ReadOnly<u32>),
            (0x83c => pub recovery_device_status_5: tock_registers::registers::ReadOnly<u32>),
            (0x840 => pub recovery_device_status_6: tock_registers::registers::ReadOnly<u32>),
            (0x844 => pub recovery_device_status_7: tock_registers::registers::ReadOnly<u32>),
            (0x848 => pub recovery_device_status_8: tock_registers::registers::ReadOnly<u32>),
            (0x84c => pub recovery_device_status_9: tock_registers::registers::ReadOnly<u32>),
            (0x850 => pub recovery_device_status_10: tock_registers::registers::ReadOnly<u32>),
            (0x854 => pub recovery_device_status_11: tock_registers::registers::ReadOnly<u32>),
            (0x858 => pub recovery_device_status_12: tock_registers::registers::ReadOnly<u32>),
            (0x85c => pub recovery_device_status_13: tock_registers::registers::ReadOnly<u32>),
            (0x860 => pub recovery_device_status_14: tock_registers::registers::ReadOnly<u32>),
            (0x864 => pub recovery_device_status_15: tock_registers::registers::ReadOnly<u32>),
            (0x868 => pub recovery_device_reset: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::DeviceReset::Register>),
            (0x86c => pub recovery_recovery_ctrl: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::RecoveryCtrl::Register>),
            (0x870 => pub recovery_recovery_status: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::RecoveryStatus::Register>),
            (0x874 => pub recovery_hw_status: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::HwStatus::Register>),
            (0x878 => _reserved1),
            (0x984 => pub recovery_indirect_fifo_ctrl_0: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::IndirectFifoCtrl0::Register>),
            (0x988 => pub recovery_indirect_fifo_ctrl_1: tock_registers::registers::ReadWrite<u32>),
            (0x98c => pub recovery_indirect_fifo_status_0: tock_registers::registers::ReadOnly<u32, crate::usb_combo::bits::IndirectFifoStatus0::Register>),
            (0x990 => pub recovery_indirect_fifo_status_1: tock_registers::registers::ReadOnly<u32>),
            (0x994 => pub recovery_indirect_fifo_status_2: tock_registers::registers::ReadOnly<u32>),
            (0x998 => pub recovery_indirect_fifo_status_3: tock_registers::registers::ReadOnly<u32>),
            (0x99c => pub recovery_indirect_fifo_status_4: tock_registers::registers::ReadOnly<u32>),
            (0x9a0 => pub recovery_indirect_fifo_data: tock_registers::registers::ReadOnly<u32>),
            (0x9a4 => pub recovery_vendor: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::Vendor::Register>),
            (0x9a8 => _reserved2),
            (0xa00 => pub recovery_caliptra_ctrl: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::CaliptraCtrl::Register>),
            (0xa04 => pub recovery_caliptra_status: tock_registers::registers::ReadOnly<u32, crate::usb_combo::bits::CaliptraStatus::Register>),
            (0xa08 => _reserved3),
            (0xffc => pub recovery_window_pad: tock_registers::registers::ReadOnly<u32>),
            (0x1000 => pub hub_descriptor_low: [tock_registers::registers::ReadWrite<u32>; 15]),
            (0x103c => pub hub_control: tock_registers::registers::ReadWrite<u32, crate::usb_combo::bits::Control::Register>),
            (0x1040 => pub hub_descriptor_high: [tock_registers::registers::ReadWrite<u32>; 156]),
            (0x12b0 => @END),
        }
    }
}
