// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at dfa6c631dbfc00c8e0c7e6b256619d03d74f0bdc
//
pub mod axicdma;
pub mod doe_mbox;
pub mod el2_pic;
pub mod ethernet;
pub mod i3c;
pub mod i3c1;
pub mod lc;
pub mod mbox;
pub mod mci;
pub mod otp;
pub mod primary_flash;
pub mod root_bus;
pub mod secondary_flash;
pub mod sha512_acc;
pub mod soc;
pub mod stub_warnings;
pub mod uart;
pub mod usb_combo;
pub mod usb_dev0_mem;
pub mod usb_dev1;
pub mod usb_dev1_mem;
pub mod usbdev;
