// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 9022fc2a57bb9af2f3ebc2376b98a807812e2e0f
//
#[allow(unused_imports)]
use tock_registers::interfaces::{Readable, Writeable};
pub trait NetworkMboxPeripheral {
    fn set_dma_ram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn set_dma_rom_sram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn register_event_channels(
        &mut self,
        _events_to_caliptra: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_caliptra: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
        _events_to_mcu: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_mcu: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
    ) {
    }
    fn poll(&mut self) {}
    fn warm_reset(&mut self) {}
    fn update_reset(&mut self) {}
    fn generated(&mut self) -> Option<&mut NetworkMboxGenerated> {
        None
    }
    fn read_network_mbox_sram(&mut self, index: usize) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: read network_mbox::network_mbox_sram[{}]",
                index
            );
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_sram(index);
        }
        0
    }
    fn write_network_mbox_sram(&mut self, val: caliptra_emu_types::RvData, index: usize) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Non-functional register stub: write network_mbox::network_mbox_sram[{}] = 0x{:08x}" , index , val);
        }
        if let Some(generated) = self.generated() {
            generated.write_network_mbox_sram(val, index);
        }
    }
    fn read_network_mbox_lock(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxLock::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read network_mbox::network_mbox_lock");
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_lock();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_network_mbox_user(&mut self) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read network_mbox::network_mbox_user");
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_user();
        }
        0
    }
    fn read_network_mbox_target_user(&mut self) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: read network_mbox::network_mbox_target_user"
            );
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_target_user();
        }
        0
    }
    fn write_network_mbox_target_user(&mut self, val: caliptra_emu_types::RvData) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Non-functional register stub: write network_mbox::network_mbox_target_user = 0x{:08x}" , val);
        }
        if let Some(generated) = self.generated() {
            generated.write_network_mbox_target_user(val);
        }
    }
    fn read_network_mbox_target_user_valid(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxTargetUserValid::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Non-functional register stub: read network_mbox::network_mbox_target_user_valid");
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_target_user_valid();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_network_mbox_target_user_valid(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::network_mbox::bits::NetworkMboxTargetUserValid::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Non-functional register stub: write network_mbox::network_mbox_target_user_valid = 0x{:08x}" , val . reg . get ());
        }
        if let Some(generated) = self.generated() {
            generated.write_network_mbox_target_user_valid(val);
        }
    }
    fn read_network_mbox_cmd(&mut self) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read network_mbox::network_mbox_cmd");
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_cmd();
        }
        0
    }
    fn write_network_mbox_cmd(&mut self, val: caliptra_emu_types::RvData) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Non-functional register stub: write network_mbox::network_mbox_cmd = 0x{:08x}" , val);
        }
        if let Some(generated) = self.generated() {
            generated.write_network_mbox_cmd(val);
        }
    }
    fn read_network_mbox_dlen(&mut self) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read network_mbox::network_mbox_dlen");
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_dlen();
        }
        0
    }
    fn write_network_mbox_dlen(&mut self, val: caliptra_emu_types::RvData) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Non-functional register stub: write network_mbox::network_mbox_dlen = 0x{:08x}" , val);
        }
        if let Some(generated) = self.generated() {
            generated.write_network_mbox_dlen(val);
        }
    }
    fn read_network_mbox_execute(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxExecute::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: read network_mbox::network_mbox_execute"
            );
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_execute();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_network_mbox_execute(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::network_mbox::bits::NetworkMboxExecute::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Non-functional register stub: write network_mbox::network_mbox_execute = 0x{:08x}" , val . reg . get ());
        }
        if let Some(generated) = self.generated() {
            generated.write_network_mbox_execute(val);
        }
    }
    fn read_network_mbox_target_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxTargetStatus::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: read network_mbox::network_mbox_target_status"
            );
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_target_status();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_network_mbox_target_status(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::network_mbox::bits::NetworkMboxTargetStatus::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Non-functional register stub: write network_mbox::network_mbox_target_status = 0x{:08x}" , val . reg . get ());
        }
        if let Some(generated) = self.generated() {
            generated.write_network_mbox_target_status(val);
        }
    }
    fn read_network_mbox_cmd_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxCmdStatus::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: read network_mbox::network_mbox_cmd_status"
            );
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_cmd_status();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_network_mbox_cmd_status(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::network_mbox::bits::NetworkMboxCmdStatus::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Non-functional register stub: write network_mbox::network_mbox_cmd_status = 0x{:08x}" , val . reg . get ());
        }
        if let Some(generated) = self.generated() {
            generated.write_network_mbox_cmd_status(val);
        }
    }
    fn read_network_mbox_hw_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxHwStatus::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: read network_mbox::network_mbox_hw_status"
            );
        }
        if let Some(generated) = self.generated() {
            return generated.read_network_mbox_hw_status();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
}
#[derive(Clone, Debug)]
pub struct NetworkMboxGenerated {
    network_mbox_sram: Vec<caliptra_emu_types::RvData>,
    network_mbox_lock: caliptra_emu_types::RvData,
    network_mbox_user: caliptra_emu_types::RvData,
    network_mbox_target_user: caliptra_emu_types::RvData,
    network_mbox_target_user_valid: caliptra_emu_types::RvData,
    network_mbox_cmd: caliptra_emu_types::RvData,
    network_mbox_dlen: caliptra_emu_types::RvData,
    network_mbox_execute: caliptra_emu_types::RvData,
    network_mbox_target_status: caliptra_emu_types::RvData,
    network_mbox_cmd_status: caliptra_emu_types::RvData,
    network_mbox_hw_status: caliptra_emu_types::RvData,
}
impl Default for NetworkMboxGenerated {
    fn default() -> Self {
        Self {
            network_mbox_sram: vec![0 as caliptra_emu_types::RvData; 524288],
            network_mbox_lock: 0 as caliptra_emu_types::RvData,
            network_mbox_user: 0 as caliptra_emu_types::RvData,
            network_mbox_target_user: 0 as caliptra_emu_types::RvData,
            network_mbox_target_user_valid: 0 as caliptra_emu_types::RvData,
            network_mbox_cmd: 0 as caliptra_emu_types::RvData,
            network_mbox_dlen: 0 as caliptra_emu_types::RvData,
            network_mbox_execute: 0 as caliptra_emu_types::RvData,
            network_mbox_target_status: 0 as caliptra_emu_types::RvData,
            network_mbox_cmd_status: 0 as caliptra_emu_types::RvData,
            network_mbox_hw_status: 0 as caliptra_emu_types::RvData,
        }
    }
}
impl NetworkMboxGenerated {
    pub fn new() -> Self {
        Self::default()
    }
    fn reset_state(&mut self) {
        *self = Self::default();
    }
}
impl NetworkMboxPeripheral for NetworkMboxGenerated {
    fn generated(&mut self) -> Option<&mut NetworkMboxGenerated> {
        Some(self)
    }
    fn warm_reset(&mut self) {
        self.reset_state();
    }
    fn update_reset(&mut self) {
        self.reset_state();
    }
    fn read_network_mbox_sram(&mut self, index: usize) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: read network_mbox::network_mbox_sram[{}]" , index);
        }
        self.network_mbox_sram[index]
    }
    fn write_network_mbox_sram(&mut self, val: caliptra_emu_types::RvData, index: usize) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: write network_mbox::network_mbox_sram[{}] = 0x{:08x}" , index , val);
        }
        let write_val = (val) as caliptra_emu_types::RvData;
        let current_val = self.network_mbox_sram[index];
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ffff as caliptra_emu_types::RvData));
        self.network_mbox_sram[index] = new_val;
    }
    fn read_network_mbox_lock(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxLock::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: read network_mbox::network_mbox_lock"
            );
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.network_mbox_lock)
    }
    fn read_network_mbox_user(&mut self) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: read network_mbox::network_mbox_user"
            );
        }
        self.network_mbox_user
    }
    fn read_network_mbox_target_user(&mut self) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: read network_mbox::network_mbox_target_user");
        }
        self.network_mbox_target_user
    }
    fn write_network_mbox_target_user(&mut self, val: caliptra_emu_types::RvData) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: write network_mbox::network_mbox_target_user = 0x{:08x}" , val);
        }
        let write_val = (val) as caliptra_emu_types::RvData;
        let current_val = self.network_mbox_target_user;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ffff as caliptra_emu_types::RvData));
        self.network_mbox_target_user = new_val;
    }
    fn read_network_mbox_target_user_valid(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxTargetUserValid::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: read network_mbox::network_mbox_target_user_valid");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.network_mbox_target_user_valid)
    }
    fn write_network_mbox_target_user_valid(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::network_mbox::bits::NetworkMboxTargetUserValid::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: write network_mbox::network_mbox_target_user_valid = 0x{:08x}" , val . reg . get ());
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.network_mbox_target_user_valid;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        self.network_mbox_target_user_valid = new_val;
    }
    fn read_network_mbox_cmd(&mut self) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: read network_mbox::network_mbox_cmd"
            );
        }
        self.network_mbox_cmd
    }
    fn write_network_mbox_cmd(&mut self, val: caliptra_emu_types::RvData) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: write network_mbox::network_mbox_cmd = 0x{:08x}" , val);
        }
        let write_val = (val) as caliptra_emu_types::RvData;
        let current_val = self.network_mbox_cmd;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ffff as caliptra_emu_types::RvData));
        self.network_mbox_cmd = new_val;
    }
    fn read_network_mbox_dlen(&mut self) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: read network_mbox::network_mbox_dlen"
            );
        }
        self.network_mbox_dlen
    }
    fn write_network_mbox_dlen(&mut self, val: caliptra_emu_types::RvData) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: write network_mbox::network_mbox_dlen = 0x{:08x}" , val);
        }
        let write_val = (val) as caliptra_emu_types::RvData;
        let current_val = self.network_mbox_dlen;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ffff as caliptra_emu_types::RvData));
        self.network_mbox_dlen = new_val;
    }
    fn read_network_mbox_execute(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxExecute::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: read network_mbox::network_mbox_execute"
            );
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.network_mbox_execute)
    }
    fn write_network_mbox_execute(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::network_mbox::bits::NetworkMboxExecute::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: write network_mbox::network_mbox_execute = 0x{:08x}" , val . reg . get ());
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.network_mbox_execute;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        self.network_mbox_execute = new_val;
    }
    fn read_network_mbox_target_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxTargetStatus::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: read network_mbox::network_mbox_target_status");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.network_mbox_target_status)
    }
    fn write_network_mbox_target_status(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::network_mbox::bits::NetworkMboxTargetStatus::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: write network_mbox::network_mbox_target_status = 0x{:08x}" , val . reg . get ());
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.network_mbox_target_status;
        let mut new_val = current_val;
        new_val = (new_val & !(0xf as caliptra_emu_types::RvData))
            | (write_val & (0xf as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        self.network_mbox_target_status = new_val;
    }
    fn read_network_mbox_cmd_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxCmdStatus::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: read network_mbox::network_mbox_cmd_status");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.network_mbox_cmd_status)
    }
    fn write_network_mbox_cmd_status(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::network_mbox::bits::NetworkMboxCmdStatus::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: write network_mbox::network_mbox_cmd_status = 0x{:08x}" , val . reg . get ());
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.network_mbox_cmd_status;
        let mut new_val = current_val;
        new_val = (new_val & !(0xf as caliptra_emu_types::RvData))
            | (write_val & (0xf as caliptra_emu_types::RvData));
        self.network_mbox_cmd_status = new_val;
    }
    fn read_network_mbox_hw_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::network_mbox::bits::NetworkMboxHwStatus::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: read network_mbox::network_mbox_hw_status");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.network_mbox_hw_status)
    }
}
pub struct NetworkMboxBus {
    pub periph: Box<dyn NetworkMboxPeripheral>,
}
impl caliptra_emu_bus::Bus for NetworkMboxBus {
    fn read(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
    ) -> Result<caliptra_emu_types::RvData, caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::LoadAddrMisaligned);
        }
        match addr {
            0..0x20_0000 => Ok(self.periph.read_network_mbox_sram(addr as usize / 4)),
            0x20_0000..0x20_0004 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_network_mbox_lock().reg.get(),
            )),
            0x20_0004..0x20_0008 => Ok(self.periph.read_network_mbox_user()),
            0x20_0008..0x20_000c => Ok(self.periph.read_network_mbox_target_user()),
            0x20_000c..0x20_0010 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_network_mbox_target_user_valid().reg.get(),
            )),
            0x20_0010..0x20_0014 => Ok(self.periph.read_network_mbox_cmd()),
            0x20_0014..0x20_0018 => Ok(self.periph.read_network_mbox_dlen()),
            0x20_0018..0x20_001c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_network_mbox_execute().reg.get(),
            )),
            0x20_001c..0x20_0020 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_network_mbox_target_status().reg.get(),
            )),
            0x20_0020..0x20_0024 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_network_mbox_cmd_status().reg.get(),
            )),
            0x20_0024..0x20_0028 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_network_mbox_hw_status().reg.get(),
            )),
            _ => Err(caliptra_emu_bus::BusError::LoadAccessFault),
        }
    }
    fn write(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
        val: caliptra_emu_types::RvData,
    ) -> Result<(), caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::StoreAddrMisaligned);
        }
        match addr {
            0..0x20_0000 => {
                self.periph.write_network_mbox_sram(val, addr as usize / 4);
                Ok(())
            }
            0x20_0000..0x20_0004 => Ok(()),
            0x20_0004..0x20_0008 => Ok(()),
            0x20_0008..0x20_000c => {
                self.periph.write_network_mbox_target_user(val);
                Ok(())
            }
            0x20_000c..0x20_0010 => {
                self.periph.write_network_mbox_target_user_valid(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x20_0010..0x20_0014 => {
                self.periph.write_network_mbox_cmd(val);
                Ok(())
            }
            0x20_0014..0x20_0018 => {
                self.periph.write_network_mbox_dlen(val);
                Ok(())
            }
            0x20_0018..0x20_001c => {
                self.periph
                    .write_network_mbox_execute(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x20_001c..0x20_0020 => {
                self.periph.write_network_mbox_target_status(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x20_0020..0x20_0024 => {
                self.periph
                    .write_network_mbox_cmd_status(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x20_0024..0x20_0028 => Ok(()),
            _ => Err(caliptra_emu_bus::BusError::StoreAccessFault),
        }
    }
    fn poll(&mut self) {
        self.periph.poll();
    }
    fn warm_reset(&mut self) {
        self.periph.warm_reset();
    }
    fn update_reset(&mut self) {
        self.periph.update_reset();
    }
}
