// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at dfa6c631dbfc00c8e0c7e6b256619d03d74f0bdc
//
#[allow(unused_imports)]
use tock_registers::interfaces::{Readable, Writeable};
pub trait UartPeripheral {
    fn set_dma_ram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn set_dma_rom_sram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn register_event_channels(
        &mut self,
        _events_to_caliptra: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_caliptra: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
        _events_to_mcu: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_mcu: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
    ) {
    }
    fn poll(&mut self) {}
    fn warm_reset(&mut self) {}
    fn update_reset(&mut self) {}
    fn generated(&mut self) -> Option<&mut UartGenerated> {
        None
    }
    fn read_intr_state(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::IntrState::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read uart::intr_state");
        }
        if let Some(generated) = self.generated() {
            return generated.read_intr_state();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_intr_state(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::IntrState::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write uart::intr_state = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_intr_state(val);
        }
    }
    fn read_intr_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::IntrEnable::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read uart::intr_enable");
        }
        if let Some(generated) = self.generated() {
            return generated.read_intr_enable();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_intr_enable(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::IntrEnable::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write uart::intr_enable = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_intr_enable(val);
        }
    }
    fn write_intr_test(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::IntrTest::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write uart::intr_test = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_intr_test(val);
        }
    }
    fn read_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::Ctrl::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read uart::ctrl");
        }
        if let Some(generated) = self.generated() {
            return generated.read_ctrl();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_ctrl(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::Ctrl::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write uart::ctrl = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_ctrl(val);
        }
    }
    fn read_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::Status::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read uart::status");
        }
        if let Some(generated) = self.generated() {
            return generated.read_status();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_rdata(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::Rdata::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read uart::rdata");
        }
        if let Some(generated) = self.generated() {
            return generated.read_rdata();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_wdata(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::Wdata::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write uart::wdata = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_wdata(val);
        }
    }
    fn read_fifo_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::FifoCtrl::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read uart::fifo_ctrl");
        }
        if let Some(generated) = self.generated() {
            return generated.read_fifo_ctrl();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_fifo_ctrl(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::FifoCtrl::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write uart::fifo_ctrl = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_fifo_ctrl(val);
        }
    }
    fn read_fifo_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::FifoStatus::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read uart::fifo_status");
        }
        if let Some(generated) = self.generated() {
            return generated.read_fifo_status();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_ovrd(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::Ovrd::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read uart::ovrd");
        }
        if let Some(generated) = self.generated() {
            return generated.read_ovrd();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_ovrd(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::Ovrd::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write uart::ovrd = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_ovrd(val);
        }
    }
    fn read_val(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::Val::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read uart::val");
        }
        if let Some(generated) = self.generated() {
            return generated.read_val();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_timeout_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::TimeoutCtrl::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read uart::timeout_ctrl");
        }
        if let Some(generated) = self.generated() {
            return generated.read_timeout_ctrl();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_timeout_ctrl(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::TimeoutCtrl::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write uart::timeout_ctrl = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_timeout_ctrl(val);
        }
    }
}
#[derive(Clone, Debug)]
pub struct UartGenerated {
    intr_state: caliptra_emu_types::RvData,
    intr_enable: caliptra_emu_types::RvData,
    intr_test: caliptra_emu_types::RvData,
    ctrl: caliptra_emu_types::RvData,
    status: caliptra_emu_types::RvData,
    rdata: caliptra_emu_types::RvData,
    wdata: caliptra_emu_types::RvData,
    fifo_ctrl: caliptra_emu_types::RvData,
    fifo_status: caliptra_emu_types::RvData,
    ovrd: caliptra_emu_types::RvData,
    val: caliptra_emu_types::RvData,
    timeout_ctrl: caliptra_emu_types::RvData,
}
impl Default for UartGenerated {
    fn default() -> Self {
        Self {
            intr_state: 0x101 as caliptra_emu_types::RvData,
            intr_enable: 0 as caliptra_emu_types::RvData,
            intr_test: 0 as caliptra_emu_types::RvData,
            ctrl: 0 as caliptra_emu_types::RvData,
            status: 0x3c as caliptra_emu_types::RvData,
            rdata: 0 as caliptra_emu_types::RvData,
            wdata: 0 as caliptra_emu_types::RvData,
            fifo_ctrl: 0 as caliptra_emu_types::RvData,
            fifo_status: 0 as caliptra_emu_types::RvData,
            ovrd: 0 as caliptra_emu_types::RvData,
            val: 0 as caliptra_emu_types::RvData,
            timeout_ctrl: 0 as caliptra_emu_types::RvData,
        }
    }
}
impl UartGenerated {
    pub fn new() -> Self {
        Self::default()
    }
    fn reset_state(&mut self) {
        *self = Self::default();
    }
}
impl UartPeripheral for UartGenerated {
    fn generated(&mut self) -> Option<&mut UartGenerated> {
        Some(self)
    }
    fn warm_reset(&mut self) {
        self.reset_state();
    }
    fn update_reset(&mut self) {
        self.reset_state();
    }
    fn read_intr_state(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::IntrState::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read uart::intr_state");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.intr_state)
    }
    fn write_intr_state(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::IntrState::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write uart::intr_state = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.intr_state;
        let mut new_val = current_val;
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        self.intr_state = new_val;
    }
    fn read_intr_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::IntrEnable::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read uart::intr_enable");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.intr_enable)
    }
    fn write_intr_enable(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::IntrEnable::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write uart::intr_enable = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.intr_enable;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        self.intr_enable = new_val;
    }
    fn write_intr_test(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::IntrTest::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write uart::intr_test = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.intr_test;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        self.intr_test = new_val;
    }
    fn read_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::Ctrl::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read uart::ctrl");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.ctrl)
    }
    fn write_ctrl(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::Ctrl::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write uart::ctrl = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.ctrl;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x300 as caliptra_emu_types::RvData))
            | (write_val & (0x300 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xffff_0000 as caliptra_emu_types::RvData))
            | (write_val & (0xffff_0000 as caliptra_emu_types::RvData));
        self.ctrl = new_val;
    }
    fn read_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::Status::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read uart::status");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.status)
    }
    fn read_rdata(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::Rdata::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read uart::rdata");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.rdata)
    }
    fn write_wdata(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::Wdata::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write uart::wdata = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.wdata;
        let mut new_val = current_val;
        new_val = (new_val & !(0xff as caliptra_emu_types::RvData))
            | (write_val & (0xff as caliptra_emu_types::RvData));
        self.wdata = new_val;
    }
    fn read_fifo_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::FifoCtrl::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read uart::fifo_ctrl");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.fifo_ctrl)
    }
    fn write_fifo_ctrl(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::FifoCtrl::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write uart::fifo_ctrl = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.fifo_ctrl;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1c as caliptra_emu_types::RvData))
            | (write_val & (0x1c as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xe0 as caliptra_emu_types::RvData))
            | (write_val & (0xe0 as caliptra_emu_types::RvData));
        self.fifo_ctrl = new_val;
    }
    fn read_fifo_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::FifoStatus::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read uart::fifo_status");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.fifo_status)
    }
    fn read_ovrd(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::Ovrd::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read uart::ovrd");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.ovrd)
    }
    fn write_ovrd(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::Ovrd::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write uart::ovrd = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.ovrd;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        self.ovrd = new_val;
    }
    fn read_val(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::Val::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read uart::val");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.val)
    }
    fn read_timeout_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::uart::bits::TimeoutCtrl::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read uart::timeout_ctrl");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.timeout_ctrl)
    }
    fn write_timeout_ctrl(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::uart::bits::TimeoutCtrl::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write uart::timeout_ctrl = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.timeout_ctrl;
        let mut new_val = current_val;
        new_val = (new_val & !(0xff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xff_ffff as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.timeout_ctrl = new_val;
    }
}
pub struct UartBus {
    pub periph: Box<dyn UartPeripheral>,
}
impl caliptra_emu_bus::Bus for UartBus {
    fn read(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
    ) -> Result<caliptra_emu_types::RvData, caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::LoadAddrMisaligned);
        }
        match addr {
            0..4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_intr_state().reg.get(),
            )),
            4..8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_intr_enable().reg.get(),
            )),
            0xc..0x10 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_ctrl().reg.get(),
            )),
            0x10..0x14 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_status().reg.get(),
            )),
            0x14..0x18 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_rdata().reg.get(),
            )),
            0x1c..0x20 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_fifo_ctrl().reg.get(),
            )),
            0x20..0x24 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_fifo_status().reg.get(),
            )),
            0x24..0x28 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_ovrd().reg.get(),
            )),
            0x28..0x2c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_val().reg.get(),
            )),
            0x2c..0x30 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_timeout_ctrl().reg.get(),
            )),
            _ => Err(caliptra_emu_bus::BusError::LoadAccessFault),
        }
    }
    fn write(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
        val: caliptra_emu_types::RvData,
    ) -> Result<(), caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::StoreAddrMisaligned);
        }
        match addr {
            0..4 => {
                self.periph
                    .write_intr_state(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            4..8 => {
                self.periph
                    .write_intr_enable(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            8..0xc => {
                self.periph
                    .write_intr_test(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0xc..0x10 => {
                self.periph
                    .write_ctrl(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x10..0x14 => Ok(()),
            0x14..0x18 => Ok(()),
            0x18..0x1c => {
                self.periph
                    .write_wdata(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x1c..0x20 => {
                self.periph
                    .write_fifo_ctrl(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x20..0x24 => Ok(()),
            0x24..0x28 => {
                self.periph
                    .write_ovrd(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x28..0x2c => Ok(()),
            0x2c..0x30 => {
                self.periph
                    .write_timeout_ctrl(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            _ => Err(caliptra_emu_bus::BusError::StoreAccessFault),
        }
    }
    fn poll(&mut self) {
        self.periph.poll();
    }
    fn warm_reset(&mut self) {
        self.periph.warm_reset();
    }
    fn update_reset(&mut self) {
        self.periph.update_reset();
    }
}
