// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at dfa6c631dbfc00c8e0c7e6b256619d03d74f0bdc
//
#[allow(unused_imports)]
use tock_registers::interfaces::{Readable, Writeable};
pub trait UsbDev1Peripheral {
    fn set_dma_ram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn set_dma_rom_sram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn register_event_channels(
        &mut self,
        _events_to_caliptra: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_caliptra: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
        _events_to_mcu: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_mcu: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
    ) {
    }
    fn poll(&mut self) {}
    fn warm_reset(&mut self) {}
    fn update_reset(&mut self) {}
    fn generated(&mut self) -> Option<&mut UsbDev1Generated> {
        None
    }
    fn read_devcmdstat(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::DevcmdstatT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::devcmdstat");
        }
        if let Some(generated) = self.generated() {
            return generated.read_devcmdstat();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_devcmdstat(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::DevcmdstatT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::devcmdstat = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_devcmdstat(val);
        }
    }
    fn read_info(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::InfoT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::info");
        }
        if let Some(generated) = self.generated() {
            return generated.read_info();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_info(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::InfoT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::info = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_info(val);
        }
    }
    fn read_epliststart(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::EpliststartT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::epliststart");
        }
        if let Some(generated) = self.generated() {
            return generated.read_epliststart();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_epliststart(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::EpliststartT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::epliststart = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_epliststart(val);
        }
    }
    fn read_databufstart(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::DatabufstartT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::databufstart");
        }
        if let Some(generated) = self.generated() {
            return generated.read_databufstart();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_databufstart(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::DatabufstartT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::databufstart = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_databufstart(val);
        }
    }
    fn read_lpm(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::LpmT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::lpm");
        }
        if let Some(generated) = self.generated() {
            return generated.read_lpm();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_lpm(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::LpmT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::lpm = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_lpm(val);
        }
    }
    fn read_epskip(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::EpskipT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::epskip");
        }
        if let Some(generated) = self.generated() {
            return generated.read_epskip();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_epskip(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::EpskipT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::epskip = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_epskip(val);
        }
    }
    fn read_epinuse(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::EpinuseT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::epinuse");
        }
        if let Some(generated) = self.generated() {
            return generated.read_epinuse();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_epinuse(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::EpinuseT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::epinuse = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_epinuse(val);
        }
    }
    fn read_epbufcfg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::EpbufcfgT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::epbufcfg");
        }
        if let Some(generated) = self.generated() {
            return generated.read_epbufcfg();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_epbufcfg(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::EpbufcfgT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::epbufcfg = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_epbufcfg(val);
        }
    }
    fn read_intstat(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::IntstatT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::intstat");
        }
        if let Some(generated) = self.generated() {
            return generated.read_intstat();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_intstat(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::IntstatT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::intstat = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_intstat(val);
        }
    }
    fn read_inten(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::IntenT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::inten");
        }
        if let Some(generated) = self.generated() {
            return generated.read_inten();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_inten(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::IntenT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::inten = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_inten(val);
        }
    }
    fn read_intsetstat(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::Intsetstat::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::intsetstat");
        }
        if let Some(generated) = self.generated() {
            return generated.read_intsetstat();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_intsetstat(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::Intsetstat::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::intsetstat = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_intsetstat(val);
        }
    }
    fn read_introute(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::IntrouteT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::introute");
        }
        if let Some(generated) = self.generated() {
            return generated.read_introute();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_introute(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::IntrouteT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::introute = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_introute(val);
        }
    }
    fn read_config(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::ConfigT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::config");
        }
        if let Some(generated) = self.generated() {
            return generated.read_config();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_eptoggle(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::EptoggleT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::eptoggle");
        }
        if let Some(generated) = self.generated() {
            return generated.read_eptoggle();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_clkctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::ClkctrlT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::clkctrl");
        }
        if let Some(generated) = self.generated() {
            return generated.read_clkctrl();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_ulpidebug(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::UlpidebugT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Non-functional register stub: read usb_dev1::ulpidebug");
        }
        if let Some(generated) = self.generated() {
            return generated.read_ulpidebug();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_ulpidebug(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::UlpidebugT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: write usb_dev1::ulpidebug = 0x{:08x}",
                val.reg.get()
            );
        }
        if let Some(generated) = self.generated() {
            generated.write_ulpidebug(val);
        }
    }
}
#[derive(Clone, Debug)]
pub struct UsbDev1Generated {
    devcmdstat: caliptra_emu_types::RvData,
    info: caliptra_emu_types::RvData,
    epliststart: caliptra_emu_types::RvData,
    databufstart: caliptra_emu_types::RvData,
    lpm: caliptra_emu_types::RvData,
    epskip: caliptra_emu_types::RvData,
    epinuse: caliptra_emu_types::RvData,
    epbufcfg: caliptra_emu_types::RvData,
    intstat: caliptra_emu_types::RvData,
    inten: caliptra_emu_types::RvData,
    intsetstat: caliptra_emu_types::RvData,
    introute: caliptra_emu_types::RvData,
    config: caliptra_emu_types::RvData,
    eptoggle: caliptra_emu_types::RvData,
    clkctrl: caliptra_emu_types::RvData,
    ulpidebug: caliptra_emu_types::RvData,
}
impl Default for UsbDev1Generated {
    fn default() -> Self {
        Self {
            devcmdstat: 0x800 as caliptra_emu_types::RvData,
            info: 0x200_0000 as caliptra_emu_types::RvData,
            epliststart: 0 as caliptra_emu_types::RvData,
            databufstart: 0 as caliptra_emu_types::RvData,
            lpm: 0 as caliptra_emu_types::RvData,
            epskip: 0 as caliptra_emu_types::RvData,
            epinuse: 0 as caliptra_emu_types::RvData,
            epbufcfg: 0 as caliptra_emu_types::RvData,
            intstat: 0 as caliptra_emu_types::RvData,
            inten: 0 as caliptra_emu_types::RvData,
            intsetstat: 0 as caliptra_emu_types::RvData,
            introute: 0 as caliptra_emu_types::RvData,
            config: 0x6ee as caliptra_emu_types::RvData,
            eptoggle: 0 as caliptra_emu_types::RvData,
            clkctrl: 1 as caliptra_emu_types::RvData,
            ulpidebug: 0 as caliptra_emu_types::RvData,
        }
    }
}
impl UsbDev1Generated {
    pub fn new() -> Self {
        Self::default()
    }
    fn reset_state(&mut self) {
        *self = Self::default();
    }
}
impl UsbDev1Peripheral for UsbDev1Generated {
    fn generated(&mut self) -> Option<&mut UsbDev1Generated> {
        Some(self)
    }
    fn warm_reset(&mut self) {
        self.reset_state();
    }
    fn update_reset(&mut self) {
        self.reset_state();
    }
    fn read_devcmdstat(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::DevcmdstatT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::devcmdstat");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.devcmdstat)
    }
    fn write_devcmdstat(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::DevcmdstatT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::devcmdstat = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.devcmdstat;
        let mut new_val = current_val;
        new_val = (new_val & !(0x7f as caliptra_emu_types::RvData))
            | (write_val & (0x7f as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1000 as caliptra_emu_types::RvData))
            | (write_val & (0x1000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2000 as caliptra_emu_types::RvData))
            | (write_val & (0x2000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x1_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x2_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x20_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x100_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x200_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x400_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x800_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xe000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0xe000_0000 as caliptra_emu_types::RvData));
        self.devcmdstat = new_val;
    }
    fn read_info(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::InfoT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::info");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.info)
    }
    fn write_info(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::InfoT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::info = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.info;
        let mut new_val = current_val;
        new_val = (new_val & !(0x7800 as caliptra_emu_types::RvData))
            | (write_val & (0x7800 as caliptra_emu_types::RvData));
        self.info = new_val;
    }
    fn read_epliststart(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::EpliststartT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::epliststart");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.epliststart)
    }
    fn write_epliststart(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::EpliststartT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::epliststart = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.epliststart;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ff00 as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ff00 as caliptra_emu_types::RvData));
        self.epliststart = new_val;
    }
    fn read_databufstart(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::DatabufstartT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::databufstart");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.databufstart)
    }
    fn write_databufstart(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::DatabufstartT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::databufstart = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.databufstart;
        let mut new_val = current_val;
        new_val = (new_val & !(0xfffe_0000 as caliptra_emu_types::RvData))
            | (write_val & (0xfffe_0000 as caliptra_emu_types::RvData));
        self.databufstart = new_val;
    }
    fn read_lpm(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::LpmT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::lpm");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.lpm)
    }
    fn write_lpm(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::LpmT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::lpm = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.lpm;
        let mut new_val = current_val;
        new_val = (new_val & !(0xf0 as caliptra_emu_types::RvData))
            | (write_val & (0xf0 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x1_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x2_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x4_0000 as caliptra_emu_types::RvData));
        self.lpm = new_val;
    }
    fn read_epskip(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::EpskipT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::epskip");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.epskip)
    }
    fn write_epskip(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::EpskipT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::epskip = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.epskip;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff as caliptra_emu_types::RvData));
        self.epskip = new_val;
    }
    fn read_epinuse(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::EpinuseT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::epinuse");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.epinuse)
    }
    fn write_epinuse(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::EpinuseT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::epinuse = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.epinuse;
        let mut new_val = current_val;
        new_val = (new_val & !(0xfffc as caliptra_emu_types::RvData))
            | (write_val & (0xfffc as caliptra_emu_types::RvData));
        self.epinuse = new_val;
    }
    fn read_epbufcfg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::EpbufcfgT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::epbufcfg");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.epbufcfg)
    }
    fn write_epbufcfg(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::EpbufcfgT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::epbufcfg = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.epbufcfg;
        let mut new_val = current_val;
        new_val = (new_val & !(0xfffc as caliptra_emu_types::RvData))
            | (write_val & (0xfffc as caliptra_emu_types::RvData));
        self.epbufcfg = new_val;
    }
    fn read_intstat(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::IntstatT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::intstat");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.intstat)
    }
    fn write_intstat(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::IntstatT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::intstat = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.intstat;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xf000 as caliptra_emu_types::RvData))
            | (write_val & (0xf000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.intstat = new_val;
    }
    fn read_inten(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::IntenT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::inten");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.inten)
    }
    fn write_inten(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::IntenT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::inten = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.inten;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.inten = new_val;
    }
    fn read_intsetstat(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::Intsetstat::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::intsetstat");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.intsetstat)
    }
    fn write_intsetstat(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::Intsetstat::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::intsetstat = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.intsetstat;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.intsetstat = new_val;
    }
    fn read_introute(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::IntrouteT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::introute");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.introute)
    }
    fn write_introute(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::IntrouteT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::introute = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.introute;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.introute = new_val;
    }
    fn read_config(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::ConfigT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::config");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.config)
    }
    fn read_eptoggle(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::EptoggleT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::eptoggle");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.eptoggle)
    }
    fn read_clkctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::ClkctrlT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::clkctrl");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.clkctrl)
    }
    fn read_ulpidebug(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        caliptra_mcu_registers_generated::usb_dev1::bits::UlpidebugT::Register,
    > {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!("[EMU] Generated default register handler: read usb_dev1::ulpidebug");
        }
        caliptra_emu_bus::ReadWriteRegister::new(self.ulpidebug)
    }
    fn write_ulpidebug(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            caliptra_mcu_registers_generated::usb_dev1::bits::UlpidebugT::Register,
        >,
    ) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: write usb_dev1::ulpidebug = 0x{:08x}",
                val.reg.get()
            );
        }
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.ulpidebug;
        let mut new_val = current_val;
        new_val = (new_val & !(0xf as caliptra_emu_types::RvData))
            | (write_val & (0xf as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xf0 as caliptra_emu_types::RvData))
            | (write_val & (0xf0 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xff00 as caliptra_emu_types::RvData))
            | (write_val & (0xff00 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xff_0000 as caliptra_emu_types::RvData))
            | (write_val & (0xff_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x100_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x200_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.ulpidebug = new_val;
    }
}
pub struct UsbDev1Bus {
    pub periph: Box<dyn UsbDev1Peripheral>,
}
impl caliptra_emu_bus::Bus for UsbDev1Bus {
    fn read(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
    ) -> Result<caliptra_emu_types::RvData, caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::LoadAddrMisaligned);
        }
        match addr {
            0..4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_devcmdstat().reg.get(),
            )),
            4..8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_info().reg.get(),
            )),
            8..0xc => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_epliststart().reg.get(),
            )),
            0xc..0x10 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_databufstart().reg.get(),
            )),
            0x10..0x14 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_lpm().reg.get(),
            )),
            0x14..0x18 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_epskip().reg.get(),
            )),
            0x18..0x1c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_epinuse().reg.get(),
            )),
            0x1c..0x20 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_epbufcfg().reg.get(),
            )),
            0x20..0x24 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_intstat().reg.get(),
            )),
            0x24..0x28 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_inten().reg.get(),
            )),
            0x28..0x2c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_intsetstat().reg.get(),
            )),
            0x2c..0x30 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_introute().reg.get(),
            )),
            0x30..0x34 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_config().reg.get(),
            )),
            0x34..0x38 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_eptoggle().reg.get(),
            )),
            0x38..0x3c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_clkctrl().reg.get(),
            )),
            0x3c..0x40 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_ulpidebug().reg.get(),
            )),
            _ => Err(caliptra_emu_bus::BusError::LoadAccessFault),
        }
    }
    fn write(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
        val: caliptra_emu_types::RvData,
    ) -> Result<(), caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::StoreAddrMisaligned);
        }
        match addr {
            0..4 => {
                self.periph
                    .write_devcmdstat(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            4..8 => {
                self.periph
                    .write_info(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            8..0xc => {
                self.periph
                    .write_epliststart(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0xc..0x10 => {
                self.periph
                    .write_databufstart(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x10..0x14 => {
                self.periph
                    .write_lpm(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x14..0x18 => {
                self.periph
                    .write_epskip(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x18..0x1c => {
                self.periph
                    .write_epinuse(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x1c..0x20 => {
                self.periph
                    .write_epbufcfg(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x20..0x24 => {
                self.periph
                    .write_intstat(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x24..0x28 => {
                self.periph
                    .write_inten(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x28..0x2c => {
                self.periph
                    .write_intsetstat(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x2c..0x30 => {
                self.periph
                    .write_introute(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x30..0x34 => Ok(()),
            0x34..0x38 => Ok(()),
            0x38..0x3c => Ok(()),
            0x3c..0x40 => {
                self.periph
                    .write_ulpidebug(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            _ => Err(caliptra_emu_bus::BusError::StoreAccessFault),
        }
    }
    fn poll(&mut self) {
        self.periph.poll();
    }
    fn warm_reset(&mut self) {
        self.periph.warm_reset();
    }
    fn update_reset(&mut self) {
        self.periph.update_reset();
    }
}
