// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at dfa6c631dbfc00c8e0c7e6b256619d03d74f0bdc
//
#[allow(unused_imports)]
use tock_registers::interfaces::{Readable, Writeable};
pub trait UsbDev0MemPeripheral {
    fn set_dma_ram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn set_dma_rom_sram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn register_event_channels(
        &mut self,
        _events_to_caliptra: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_caliptra: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
        _events_to_mcu: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_mcu: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
    ) {
    }
    fn poll(&mut self) {}
    fn warm_reset(&mut self) {}
    fn update_reset(&mut self) {}
    fn generated(&mut self) -> Option<&mut UsbDev0MemGenerated> {
        None
    }
    fn read_usb_dev0_mem(&mut self, index: usize) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Non-functional register stub: read usb_dev0_mem::usb_dev0_mem[{}]",
                index
            );
        }
        if let Some(generated) = self.generated() {
            return generated.read_usb_dev0_mem(index);
        }
        0
    }
    fn write_usb_dev0_mem(&mut self, val: caliptra_emu_types::RvData, index: usize) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Non-functional register stub: write usb_dev0_mem::usb_dev0_mem[{}] = 0x{:08x}" , index , val);
        }
        if let Some(generated) = self.generated() {
            generated.write_usb_dev0_mem(val, index);
        }
    }
}
#[derive(Clone, Debug)]
pub struct UsbDev0MemGenerated {
    usb_dev0_mem: Vec<caliptra_emu_types::RvData>,
}
impl Default for UsbDev0MemGenerated {
    fn default() -> Self {
        Self {
            usb_dev0_mem: vec![0 as caliptra_emu_types::RvData; 16384],
        }
    }
}
impl UsbDev0MemGenerated {
    pub fn new() -> Self {
        Self::default()
    }
    fn reset_state(&mut self) {
        *self = Self::default();
    }
}
impl UsbDev0MemPeripheral for UsbDev0MemGenerated {
    fn generated(&mut self) -> Option<&mut UsbDev0MemGenerated> {
        Some(self)
    }
    fn warm_reset(&mut self) {
        self.reset_state();
    }
    fn update_reset(&mut self) {
        self.reset_state();
    }
    fn read_usb_dev0_mem(&mut self, index: usize) -> caliptra_emu_types::RvData {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln!(
                "[EMU] Generated default register handler: read usb_dev0_mem::usb_dev0_mem[{}]",
                index
            );
        }
        self.usb_dev0_mem[index]
    }
    fn write_usb_dev0_mem(&mut self, val: caliptra_emu_types::RvData, index: usize) {
        if crate::stub_warnings::stub_warnings_enabled() {
            eprintln ! ("[EMU] Generated default register handler: write usb_dev0_mem::usb_dev0_mem[{}] = 0x{:08x}" , index , val);
        }
        let write_val = (val) as caliptra_emu_types::RvData;
        let current_val = self.usb_dev0_mem[index];
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ffff as caliptra_emu_types::RvData));
        self.usb_dev0_mem[index] = new_val;
    }
}
pub struct UsbDev0MemBus {
    pub periph: Box<dyn UsbDev0MemPeripheral>,
}
impl caliptra_emu_bus::Bus for UsbDev0MemBus {
    fn read(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
    ) -> Result<caliptra_emu_types::RvData, caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::LoadAddrMisaligned);
        }
        match addr {
            0..0x1_0000 => Ok(self.periph.read_usb_dev0_mem(addr as usize / 4)),
            _ => Err(caliptra_emu_bus::BusError::LoadAccessFault),
        }
    }
    fn write(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
        val: caliptra_emu_types::RvData,
    ) -> Result<(), caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::StoreAddrMisaligned);
        }
        match addr {
            0..0x1_0000 => {
                self.periph.write_usb_dev0_mem(val, addr as usize / 4);
                Ok(())
            }
            _ => Err(caliptra_emu_bus::BusError::StoreAccessFault),
        }
    }
    fn poll(&mut self) {
        self.periph.poll();
    }
    fn warm_reset(&mut self) {
        self.periph.warm_reset();
    }
    fn update_reset(&mut self) {
        self.periph.update_reset();
    }
}
